name: CMake on multiple platforms

on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:
    branches:
      - master
      - main
      - dev

jobs:
  windows-msvc-debug:
    runs-on: [windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: "msvc"
          vcvarshall: true
          cmake: true
          ninja: true
          vcpkg: true

      - name: Configure
        run: cmake --preset windows-msvc-debug

      - name: Build
        run: cmake --build out/build/windows-msvc-debug --target RUN_ALL_TARGETS

  windows-msvc-dev:
    runs-on: [windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: "msvc"
          vcvarshall: true
          cmake: true
          ninja: true
          vcpkg: true

      - name: Configure
        run: cmake --preset windows-msvc-dev

      - name: Build
        run: cmake --build out/build/windows-msvc-dev --target RUN_ALL_TARGETS

  windows-msvc-release:
    runs-on: [windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: "msvc"
          vcvarshall: true
          cmake: true
          ninja: true
          vcpkg: true

      - name: Configure
        run: cmake --preset windows-msvc-release

      - name: Build
        run: cmake --build out/build/windows-msvc-release --target RUN_ALL_TARGETS

  windows-clang-debug:
    runs-on: [windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          cmake: true
          ninja: true
          vcpkg: true

      - name: Configure
        run: cmake --preset windows-clang-debug

      - name: Build
        run: cmake --build out/build/windows-clang-debug --target RUN_ALL_TARGETS

  windows-clang-dev:
    runs-on: [windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          cmake: true
          ninja: true
          vcpkg: true

      - name: Configure
        run: cmake --preset windows-clang-dev

      - name: Build
        run: cmake --build out/build/windows-clang-dev --target RUN_ALL_TARGETS

  windows-clang-release:
    runs-on: [windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          cmake: true
          ninja: true
          vcpkg: true

      - name: Configure
        run: cmake --preset windows-clang-release

      - name: Build
        run: cmake --build out/build/windows-clang-release --target RUN_ALL_TARGETS

  linux-clang-debug:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: cmake --preset linux-clang-debug

      - name: Build
        run: cmake --build out/build/linux-clang-debug --target RUN_ALL_TARGETS

  linux-clang-dev:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: cmake --preset linux-clang-dev

      - name: Build
        run: cmake --build out/build/linux-clang-dev --target RUN_ALL_TARGETS

  linux-clang-release:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: cmake --preset linux-clang-release

      - name: Build
        run: cmake --build out/build/linux-clang-release --target RUN_ALL_TARGETS

  linux-gcc-debug:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: cmake --preset linux-gcc-debug

      - name: Build
        run: cmake --build out/build/linux-gcc-debug --target RUN_ALL_TARGETS

  linux-gcc-dev:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: cmake --preset linux-gcc-dev

      - name: Build
        run: cmake --build out/build/linux-gcc-dev --target RUN_ALL_TARGETS

  linux-gcc-release:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: cmake --preset linux-gcc-release

      - name: Build
        run: cmake --build out/build/linux-gcc-release --target RUN_ALL_TARGETS
