#!/bin/sh

echo "=== Running post-update git-hooks ==="

# # An example hook script to prepare a packed repository for use over
# # dumb transports.
# #
# # To enable this hook, rename this file to "post-update".

# # exec git update-server-info
